# Generated by Django 4.0.5 on 2022-06-12 14:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_number_employee', models.IntegerField()),
                ('full_name_employee', models.CharField(max_length=120)),
                ('position_employee', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_equipment', models.CharField(blank=True, max_length=120)),
                ('number_equipment', models.IntegerField()),
                ('name_equipment', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('login', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewing_for_inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_reviewing', models.DateField(default=datetime.date.today)),
                ('result_of_reviewing', models.CharField(max_length=120)),
                ('reason_of_reviewing', models.CharField(max_length=120)),
                ('full_name_reviewing_employee', models.CharField(max_length=120)),
                ('equipment_of_reviewing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plots', models.IntegerField()),
                ('name_plots', models.CharField(max_length=120)),
                ('equipment_on_plots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Accounting_for_failure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_accounting', models.DateField(default=datetime.date.today)),
                ('reason_of_accounting', models.CharField(max_length=120)),
                ('full_name_accounting_employee', models.CharField(max_length=120)),
                ('equipment_of_accounting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.equipment')),
            ],
        ),
    ]
